global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: fancyweboperator
    static_configs:
      - targets: ['localhost:9090']
  - job_name: fancyweb 
    metrics_path: /prometheus
    static_configs:
      - targets:
        - fancyweb:9091